### ISSUE TITLE
Volume mount via docker-compose file

### ISSUE THREAD

**Issue by lox** [StefanScherer/windows-docker-machine#10]
I can't for the life of me figure out how to translate the example of mounting a volume from the macOS host to the docker container to work in `docker-compose.yml`:

```bash
docker run -it -v C:$(pwd):C:$(pwd) microsoft/windowsservercore powershell
```

I get errors pretty much every way I try it in a docker-compose file that I am running via macOS (docker-compose 1.16). Any ideas?

**Comment by lox** [comment]
For instance, this works fine:

```bash
docker run --rm -it -v C:\\Users\\lachlan\\.ssh:C:\\ssh -w C:\\ssh microsoft/windowsservercore powershell
```

But then I try that in docker-compose:

```yaml
version: "3.2"

services:
  test:
    image: microsoft/windowsservercore
    volumes:
      - C:\\Users\\lachlan\\.ssh:C:\\ssh
```

and I get:

```bash
ERROR: Volume C:\\Users\\lachlan\\.ssh:C:\\ssh has incorrect format, should be external:internal[:mode]
```
