### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by Plork** [StefanScherer/windows-docker-machine#16]
I don't know if you tested this .. but I cannot get docker-compose to work via this way of working.

normal docker commands work. but when I am on my mac and try to mount volumes in the compose file I get.

`
ERROR: for db  Cannot create container for service db: invalid volume spec "C": invalid volume specification: 'C'`

```
services:
 db:
  image: microsoft/mssql-server-windows-express
  volumes:
  - ./docker/databases:C:Data
```
