### ISSUE TITLE
Can't connect to published ports from MacOS

### ISSUE THREAD

**Issue by Lyle-Alloy** [StefanScherer/windows-docker-machine#87]
I have gotten the 2022-box vagrant image up, connected to the docker host, gotten my image built and running, but I cannot seem to access the published ports from MacOS.

Here's the snippet of the `docker-compose.yml` that is getting sent to the windows host:

```yaml
    simulator:
        build:
            dockerfile: Dockerfile
            context: simulator
        ports:
        -   "7001:701"
        -   "7002:702"
        -   "7003:703"
        profiles:
        -   simulator
 ```

 and here's the output that I see from trying to poke it:
```
$docker-machine ip 2022-box
192.168.59.52

$nmap -Pn 192.168.59.52
Starting Nmap 7.92 ( https://nmap.org ) at 2022-07-22 14:13 EDT
Nmap scan report for 192.168.59.52
Host is up (0.00043s latency).
Not shown: 999 filtered tcp ports (no-response)
PORT     STATE SERVICE
3389/tcp open  ms-wbt-server

Nmap done: 1 IP address (1 host up) scanned in 4.35 seconds

$nmap -Pn 192.168.59.52 -p7001,7002,7003
Starting Nmap 7.92 ( https://nmap.org ) at 2022-07-22 14:13 EDT
Nmap scan report for 192.168.59.52
Host is up.

PORT     STATE    SERVICE
7001/tcp filtered afs3-callback
7002/tcp filtered afs3-prserver
7003/tcp filtered afs3-vlserver

Nmap done: 1 IP address (1 host up) scanned in 3.08 seconds
```

Am I missing something? Is there some sort of port forwarding that I need to tell vagrant to do? Also I noticed I can't `ping` `192.168.59.52` (and have to use the `-Pn` flag on nmap)
